import React from 'react';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import {
  Layers,
  ArrowLeft,
  Coffee,
  Package,
  ShoppingBag,
  Gift,
  Trash2,
  Calendar,
  CheckCircle2,
  DollarSign,
  ArrowDown,
  Sparkles,
  Store,
  FileSpreadsheet,
} from 'lucide-react';
import { prisma } from '@/lib/db/prisma';
import { formatCurrency, formatQuantity } from '@/lib/calculations/inventory';
import { formatDate, formatDateTime } from '@/lib/utils';

import { BatchActionsClient } from '@/components/production/BatchActionsClient';

export const revalidate = 0;

export default async function BatchDetailPage({
  params,
}: {
  params: Promise<{ batchNumber: string }>;
}) {
  const { batchNumber } = await params;

  const batch = await prisma.productionBatch.findUnique({
    where: { batchNumber },
    include: {
      product: true,
      ingredients: {
        include: { inventoryItem: true },
      },
      outputs: {
        include: { product: true },
      },
      finishedGoodsLots: {
        include: {
          transactions: {
            include: {
              lot: { include: { product: true } },
            },
            orderBy: { date: 'desc' },
          },
          saleItems: {
            include: {
              sale: { include: { cafe: true } },
            },
          },
        },
      },
      wasteRecords: true,
    },
  });

  if (!batch) {
    notFound();
  }

  const primaryLot = batch.finishedGoodsLots[0];

  // Revenue generated by this batch's lot
  const revenueGenerated = primaryLot
    ? primaryLot.saleItems.reduce((acc, si) => acc + si.total, 0)
    : 0;

  const grossProfit = revenueGenerated - batch.totalProductionCost;

  return (
    <div className="space-y-8 max-w-6xl mx-auto pb-16">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 pb-4 border-b border-zinc-800">
        <div className="flex items-center gap-3">
          <Link
            href="/production"
            className="p-2 rounded-xl bg-zinc-900 border border-zinc-800 text-zinc-400 hover:text-zinc-200 transition-colors"
          >
            <ArrowLeft className="w-4 h-4" />
          </Link>
          <div>
            <div className="flex items-center gap-2">
              <h1 className="text-xl sm:text-2xl font-black text-zinc-100 font-mono">
                {batch.batchNumber}
              </h1>
              <span className="px-2.5 py-0.5 rounded-full text-xs font-semibold bg-amber-500/15 text-amber-400 border border-amber-500/30">
                {batch.batchType}
              </span>
              <span className="px-2.5 py-0.5 rounded-full text-xs font-semibold bg-emerald-500/15 text-emerald-400 border border-emerald-500/30">
                {batch.status}
              </span>
            </div>
            <p className="text-xs text-zinc-400 mt-1">
              Production Date: {formatDate(batch.productionDate)} • Product: {batch.product.name}
            </p>
          </div>
        </div>

        <div className="flex items-center gap-2 self-start sm:self-auto">
          <BatchActionsClient batch={batch as any} />
          <Link
            href="/api/export/excel"
            className="px-3.5 py-2 rounded-xl bg-zinc-900 hover:bg-zinc-800 border border-zinc-800 text-zinc-200 text-xs font-semibold flex items-center gap-2"
          >
            <FileSpreadsheet className="w-4 h-4 text-emerald-400" />
            Export Report
          </Link>
        </div>
      </div>

      {/* 1. VISUAL 100% TRACEABILITY PIPELINE (Specification 30) */}
      <section className="p-6 rounded-3xl bg-zinc-900/90 border border-amber-500/40 space-y-6 shadow-2xl relative overflow-hidden">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2.5">
            <Sparkles className="w-5 h-5 text-amber-500" />
            <h2 className="text-sm font-extrabold uppercase tracking-wider text-zinc-100">
              End-to-End Batch Traceability Chain
            </h2>
          </div>
          <span className="text-xs font-semibold text-amber-400 bg-amber-500/10 px-2.5 py-1 rounded-full border border-amber-500/20">
            Immutable Chain of Custody
          </span>
        </div>

        {/* Diagram Flow Nodes */}
        <div className="grid grid-cols-1 md:grid-cols-4 gap-4 relative">
          {/* Node 1: Raw Materials In */}
          <div className="p-4 rounded-2xl bg-zinc-950 border border-zinc-800 space-y-2 relative">
            <div className="flex items-center gap-2 text-xs font-bold text-orange-400 uppercase">
              <Coffee className="w-4 h-4" />
              1. Raw Inputs
            </div>
            <div className="space-y-1 text-xs">
              {batch.ingredients.map((ing) => (
                <div key={ing.id} className="flex items-center justify-between text-[11px]">
                  <span className="text-zinc-300 truncate max-w-[120px]">
                    {ing.inventoryItem.name}
                  </span>
                  <span className="font-mono text-zinc-100 font-bold">
                    {ing.quantity} {ing.unit}
                  </span>
                </div>
              ))}
            </div>
            <div className="pt-2 border-t border-zinc-800 text-[10px] text-zinc-500">
              RM Cost: {formatCurrency(batch.rawMaterialCost + batch.packagingCost)}
            </div>
          </div>

          {/* Node 2: Production Batch */}
          <div className="p-4 rounded-2xl bg-zinc-950 border border-amber-500/60 space-y-2 relative shadow-lg shadow-amber-950/20">
            <div className="flex items-center gap-2 text-xs font-bold text-amber-400 uppercase">
              <Layers className="w-4 h-4" />
              2. Production Batch
            </div>
            <div className="space-y-1 text-xs">
              <div className="font-mono font-bold text-zinc-100 text-sm">
                {batch.batchNumber}
              </div>
              <div className="text-[11px] text-zinc-400">
                Output: <strong className="text-zinc-100">{batch.actualOutput} bottles</strong>
              </div>
              <div className="text-[11px] text-emerald-400 font-semibold">
                Yield: {batch.yieldPercent}%
              </div>
            </div>
            <div className="pt-2 border-t border-zinc-800 text-[10px] text-zinc-500">
              Unit Cost: {formatCurrency(batch.costPerUnit)}/bottle
            </div>
          </div>

          {/* Node 3: Finished Goods Lot */}
          <div className="p-4 rounded-2xl bg-zinc-950 border border-emerald-500/60 space-y-2 relative shadow-lg shadow-emerald-950/20">
            <div className="flex items-center gap-2 text-xs font-bold text-emerald-400 uppercase">
              <Package className="w-4 h-4" />
              3. Finished Goods Lot
            </div>
            <div className="space-y-1 text-xs">
              <div className="font-mono font-bold text-emerald-300 text-sm">
                {primaryLot?.lotNumber || 'N/A'}
              </div>
              <div className="text-[11px] text-zinc-400">
                Lot Status: <strong className="text-zinc-200">{primaryLot?.status}</strong>
              </div>
              <div className="text-[11px] text-zinc-400">
                Expiry: {formatDate(primaryLot?.expiryDate)}
              </div>
            </div>
            <div className="pt-2 border-t border-zinc-800 text-[10px] text-zinc-500">
              {primaryLot ? formatCurrency(primaryLot.quantityAvailable * primaryLot.unitCost) : '₹0'} Stock Val
            </div>
          </div>

          {/* Node 4: Downstream Distribution */}
          <div className="p-4 rounded-2xl bg-zinc-950 border border-zinc-800 space-y-2 relative">
            <div className="flex items-center gap-2 text-xs font-bold text-sky-400 uppercase">
              <ShoppingBag className="w-4 h-4" />
              4. Movement & Balance
            </div>
            <div className="space-y-1 text-xs">
              <div className="flex justify-between text-[11px]">
                <span className="text-zinc-400">Sold:</span>
                <span className="font-bold text-sky-400">{primaryLot?.quantitySold || 0} btls</span>
              </div>
              <div className="flex justify-between text-[11px]">
                <span className="text-zinc-400">Samples:</span>
                <span className="font-bold text-pink-400">{primaryLot?.quantitySampled || 0} btls</span>
              </div>
              <div className="flex justify-between text-[11px]">
                <span className="text-zinc-400">Waste:</span>
                <span className="font-bold text-rose-400">{primaryLot?.quantityWasted || 0} btls</span>
              </div>
              <div className="flex justify-between text-[11px] font-bold pt-1 border-t border-zinc-800">
                <span className="text-zinc-200">Available:</span>
                <span className="text-emerald-400 text-sm font-mono">
                  {primaryLot?.quantityAvailable || 0} btls
                </span>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* 2. FINANCIAL PERFORMANCE & BATCH INFORMATION CARDS */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
        {/* Financial Breakdown */}
        <section className="p-5 rounded-3xl bg-zinc-900/80 border border-zinc-800 space-y-4">
          <div className="flex items-center gap-2 pb-3 border-b border-zinc-800">
            <DollarSign className="w-4 h-4 text-emerald-400" />
            <h3 className="text-sm font-bold uppercase tracking-wider text-zinc-300">
              Batch Costing & Financials
            </h3>
          </div>

          <div className="grid grid-cols-2 sm:grid-cols-3 gap-3 text-xs">
            <div className="p-3 rounded-2xl bg-zinc-950/60 border border-zinc-800">
              <span className="text-[11px] text-zinc-400">Raw Materials Cost</span>
              <div className="text-base font-bold text-zinc-100 mt-0.5">
                {formatCurrency(batch.rawMaterialCost)}
              </div>
            </div>
            <div className="p-3 rounded-2xl bg-zinc-950/60 border border-zinc-800">
              <span className="text-[11px] text-zinc-400">Packaging Cost</span>
              <div className="text-base font-bold text-zinc-100 mt-0.5">
                {formatCurrency(batch.packagingCost)}
              </div>
            </div>
            <div className="p-3 rounded-2xl bg-zinc-950/60 border border-zinc-800">
              <span className="text-[11px] text-zinc-400">Total Production Cost</span>
              <div className="text-base font-bold text-amber-400 mt-0.5">
                {formatCurrency(batch.totalProductionCost)}
              </div>
            </div>
            <div className="p-3 rounded-2xl bg-zinc-950/60 border border-zinc-800">
              <span className="text-[11px] text-zinc-400">Unit Cost</span>
              <div className="text-base font-bold text-emerald-400 mt-0.5">
                {formatCurrency(batch.costPerUnit)}/ea
              </div>
            </div>
            <div className="p-3 rounded-2xl bg-zinc-950/60 border border-zinc-800">
              <span className="text-[11px] text-zinc-400">Cost Per Liter</span>
              <div className="text-base font-bold text-zinc-200 mt-0.5">
                {formatCurrency(batch.costPerLiter)}/L
              </div>
            </div>
            <div className="p-3 rounded-2xl bg-zinc-950/60 border border-zinc-800">
              <span className="text-[11px] text-zinc-400">Revenue to Date</span>
              <div className="text-base font-bold text-sky-400 mt-0.5">
                {formatCurrency(revenueGenerated)}
              </div>
            </div>
          </div>

          <div className="p-3 rounded-2xl bg-zinc-950/40 border border-zinc-800 text-xs flex items-center justify-between">
            <span className="text-zinc-400">Batch Gross Profit Contribution:</span>
            <span
              className={`font-bold font-mono text-sm ${
                grossProfit >= 0 ? 'text-emerald-400' : 'text-rose-400'
              }`}
            >
              {formatCurrency(grossProfit)}
            </span>
          </div>
        </section>

        {/* Recipe & Batch Details */}
        <section className="p-5 rounded-3xl bg-zinc-900/80 border border-zinc-800 space-y-4">
          <div className="flex items-center gap-2 pb-3 border-b border-zinc-800">
            <Layers className="w-4 h-4 text-amber-400" />
            <h3 className="text-sm font-bold uppercase tracking-wider text-zinc-300">
              Brew Specifications & Parameters
            </h3>
          </div>

          <div className="space-y-3 text-xs">
            <div>
              <span className="text-zinc-400 block font-semibold">Recipe Formulation:</span>
              <p className="text-zinc-200 mt-0.5 p-2.5 rounded-xl bg-zinc-950/60 border border-zinc-800/80">
                {batch.recipe || 'Standard 20-hour immersion extraction at 4°C.'}
              </p>
            </div>

            <div>
              <span className="text-zinc-400 block font-semibold">Batch Notes:</span>
              <p className="text-zinc-200 mt-0.5 p-2.5 rounded-xl bg-zinc-950/60 border border-zinc-800/80">
                {batch.notes || 'Batch completed with standard sensory quality metrics.'}
              </p>
            </div>
          </div>
        </section>
      </div>

      {/* 3. RAW MATERIALS CONSUMED TABLE */}
      <section className="p-6 rounded-3xl bg-zinc-900/80 border border-zinc-800 space-y-4">
        <h3 className="text-sm font-bold uppercase tracking-wider text-zinc-300 flex items-center gap-2">
          <Coffee className="w-4 h-4 text-orange-400" />
          Raw Materials Consumed in this Batch
        </h3>

        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs border-collapse">
            <thead>
              <tr className="border-b border-zinc-800 text-zinc-400 font-semibold bg-zinc-950/60">
                <th className="py-2.5 px-3">Item</th>
                <th className="py-2.5 px-3">Category</th>
                <th className="py-2.5 px-3 text-right">Quantity Consumed</th>
                <th className="py-2.5 px-3 text-right">Unit Cost</th>
                <th className="py-2.5 px-3 text-right">Total Cost</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-zinc-800/60">
              {batch.ingredients.map((ing) => (
                <tr key={ing.id} className="hover:bg-zinc-800/40">
                  <td className="py-2.5 px-3 font-semibold text-zinc-200">
                    {ing.inventoryItem.name}
                  </td>
                  <td className="py-2.5 px-3">
                    <span className="px-2 py-0.5 rounded bg-zinc-800 text-zinc-400 text-[11px]">
                      {ing.inventoryItem.category}
                    </span>
                  </td>
                  <td className="py-2.5 px-3 text-right font-mono font-bold text-zinc-100">
                    {ing.quantity} {ing.unit}
                  </td>
                  <td className="py-2.5 px-3 text-right font-mono text-zinc-400">
                    {formatCurrency(ing.unitCost)}
                  </td>
                  <td className="py-2.5 px-3 text-right font-mono font-bold text-amber-400">
                    {formatCurrency(ing.totalCost)}
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>

      {/* 4. SALES & CUSTOMER FULFILLMENT FROM THIS BATCH */}
      <section className="p-6 rounded-3xl bg-zinc-900/80 border border-zinc-800 space-y-4">
        <div className="flex items-center justify-between pb-2 border-b border-zinc-800">
          <div className="flex items-center gap-2">
            <Store className="w-4 h-4 text-purple-400" />
            <h3 className="text-sm font-bold uppercase tracking-wider text-zinc-300">
              B2B Sales & Deliveries Fulfilled from this Batch
            </h3>
          </div>
          <span className="text-xs text-zinc-400">
            {primaryLot?.saleItems.length || 0} customer orders fulfilled
          </span>
        </div>

        {primaryLot && primaryLot.saleItems.length > 0 ? (
          <div className="overflow-x-auto">
            <table className="w-full text-left text-xs">
              <thead>
                <tr className="border-b border-zinc-800 text-zinc-400 font-semibold">
                  <th className="py-2.5 px-3">Sale #</th>
                  <th className="py-2.5 px-3">Date</th>
                  <th className="py-2.5 px-3">Customer / Café</th>
                  <th className="py-2.5 px-3 text-right">Quantity</th>
                  <th className="py-2.5 px-3 text-right">Unit Price</th>
                  <th className="py-2.5 px-3 text-right">Order Revenue</th>
                  <th className="py-2.5 px-3 text-right">Gross Margin</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-zinc-800/60">
                {primaryLot.saleItems.map((si) => (
                  <tr key={si.id} className="hover:bg-zinc-800/40">
                    <td className="py-2.5 px-3 font-mono font-bold text-amber-400">
                      <Link href={`/sales#${si.sale.saleNumber}`} className="hover:underline">
                        {si.sale.saleNumber}
                      </Link>
                    </td>
                    <td className="py-2.5 px-3 text-zinc-400 font-mono">
                      {formatDate(si.sale.date)}
                    </td>
                    <td className="py-2.5 px-3 font-semibold text-zinc-200">
                      {si.sale.cafe?.name || 'Direct Customer'}
                    </td>
                    <td className="py-2.5 px-3 text-right font-mono font-bold text-zinc-100">
                      {si.quantity} btls
                    </td>
                    <td className="py-2.5 px-3 text-right font-mono text-zinc-300">
                      {formatCurrency(si.unitPrice)}
                    </td>
                    <td className="py-2.5 px-3 text-right font-mono font-bold text-emerald-400">
                      {formatCurrency(si.total)}
                    </td>
                    <td className="py-2.5 px-3 text-right font-mono font-bold text-sky-400">
                      {formatCurrency(si.grossMargin)}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        ) : (
          <div className="p-8 text-center text-zinc-500 text-xs">
            No customer sales recorded from this batch lot yet. Available for FIFO allocation.
          </div>
        )}
      </section>
    </div>
  );
}
